# Generated by Django 3.1.6 on 2021-07-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('maps_link', models.CharField(max_length=300)),
                ('area', models.CharField(max_length=100)),
                ('permission_required', models.BooleanField()),
                ('contact_management_name', models.CharField(max_length=100)),
                ('contact_management_num', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
