# Generated by Django 3.1.5 on 2021-07-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastevents',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tt',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tt',
            name='place',
            field=models.CharField(max_length=300),
        ),
    ]
