# Generated by Django 3.1.5 on 2021-07-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210721_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
