# Generated by Django 3.1.5 on 2021-07-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reported_event',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='reported_map',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
