# Generated by Django 3.1.5 on 2021-07-25 20:16

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210721_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=300)),
                ('event_name', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='reported_event',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='reported_map',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.post')),
            ],
        ),
    ]
